name: 发布软件

on:
  push: # 代码推送到main分支自动触发工作流
    branches:
      - main
  workflow_dispatch: # 手动触发

permissions: write-all # 给所有工作写权限

jobs:
  jobs_window:
    name: 构建window软件
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 读入环境信息
        run: |
          # 模拟写出一个 exe
            mkdir -p ./dist
            echo "hello world" > ./dist/hello.exe
      - name: 上传产物
        uses: actions/upload-artifact@v3
        with:
          name: window
          path: ./dist/*.exe
  jobs4:
    needs: [ jobs_window ]
    name: 发布版本
    runs-on: ubuntu-latest
    steps:
      - name: 下载产物
        id: download
        uses: actions/download-artifact@v3
        with:
          path: ./
      - name: 读入环境信息
        run: |
          echo ${{steps.download.outputs.download-path}}
          ls -R
      - uses: actions/checkout@v3
      - name: 编译环境设置 Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"
        env:
          INPUT_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          YOUR_GITHUB_REPOSITORY: duolabmeng6/qoq2
          UPFILE_LISTsTR: ./window/hello.exe,
      - name: 下载依赖文件
        run: |
          pip install PyGithub
      - name: 编译exe
        run: |
          # 读取环境变量
          echo ${{ format('INPUT_TOKEN {0}', env.INPUT_TOKEN ) }} # 版本号
          echo ${{ format('UPFILE_LISTsTR {0}', env.UPFILE_LISTsTR ) }} # 版本变更内容
          python github_action_upfile.py
